use_frameworks!

platform :ios, '14.0'

target 'icu4c-test_Example' do
  pod 'icu4c-test', :path => '../'

  target 'icu4c-test_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer_representation|
  project = installer_representation.pods_project
  project.targets.each do |target|
    if target.name == "icu4c-iosx"
      target.build_configurations.each do |config|
        target.build_settings(config.name)['VALID_ARCHS'] = "arm64 X86_64"
      end
    end
  end
end
